pipeline:
  name: PTE_IBM
  identifier: PTE_IBM
  projectIdentifier: VN
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: VikramIBM
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-latest
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Vikram_Docker
                    repo: vikramtek/harness-ibm
                    tags:
                      - latest
                    caching: true

