apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banking-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "banking-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "banking-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "banking-service.selectorLabels" . | nindent 8 }}
        version: {{ .Values.app.version | quote }}
    spec:
      serviceAccountName: {{ include "banking-service.serviceAccountName" . }}
      containers:
        - name: {{ .Values.app.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS | quote }}
          {{- if .Values.config.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "banking-service.fullname" . }}-config
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
