apiVersion: v1
kind: Service
metadata:
  name: {{ include "banking-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "banking-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "banking-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
